### ISSUE TITLE
Adding public col to v1_metadata

### ISSUE THREAD

**Issue by JesJehle** [Deadwood-ai/deadwood-api#11] opened 2024-07-24 12:14 UTC
We should add a `public` col to the v1_metadata table to indicate whether the data set is public or not, meaning if people can download and see the image.

In the old tables version, we used a public col as boolean.
this could be specified by the `upsert_metadata` route

**Comment by mmaelicke** [comment] 2024-08-05 09:42
I can implement this along with #23 #25 

To clarify here again: a non-public upload, that still receives a COG, is in fact public as the cog has the original resoultion as the last overview level.
That means, a user uploads a private image and others can't download the original, but will be able to download a jpeg comressed version of the original (in original resolution). @JesJehle @cmosig is this the intended behavior?
The only feasible alternative is to skip the COG creations. That would imply that private files cannot be viewed on the website, even not for the owner.

**Comment by cmosig** [comment] 2024-08-05 09:54
The `public` field is only for data that we currently have on our infrastructure and that is supposed to be held back until the authors do their publication with it. 

I would not give users on the website the option to make their data private imo

**Comment by mmaelicke** [comment] 2024-08-08 14:41
I will close this issue as not planned

**Closed by mmaelicke** 2024-08-08 14:41 UTC

**Comment by cmosig** [comment] 2024-08-08 15:11
Ok, probably even better. Then the public field needs to be respected when importing the data next week. 

There could be data currently in your copy that is not supposed to be public, marked appropriately with the public field. Please make sure that this data will not get public during testing, e.g. when enabling download.
